### ISSUE TITLE
Compile the project using vs2022

### ISSUE THREAD

**Issue by durongze** [intvsteve/NppHexEditor#5]
>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(25,59): error C2665: 'std::exception::exception': no overloaded function could convert all the argument types
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\vcruntime_exception.h(70,5): message : could be 'std::exception::exception(const std::exception &) noexcept'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(25,59): message : 'std::exception::exception(const std::exception &) noexcept': cannot convert argument 1 from 'const _Elem *' to 'const std::exception &'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(25,74): message : Reason: cannot convert from 'const _Elem *' to 'const std::exception'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(25,74): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\vcruntime_exception.h(57,5): message : or       'std::exception::exception(const char *const ) noexcept'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(25,59): message : 'std::exception::exception(const char *const ) noexcept': cannot convert argument 1 from 'const _Elem *' to 'const char *const '
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(25,74): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(25,59): message : while trying to match the argument list '(const _Elem *)'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(105,61): error C2665: 'std::exception::exception': no overloaded function could convert all the argument types
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\vcruntime_exception.h(70,5): message : could be 'std::exception::exception(const std::exception &) noexcept'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(105,61): message : 'std::exception::exception(const std::exception &) noexcept': cannot convert argument 1 from 'const _Elem *' to 'const std::exception &'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(105,76): message : Reason: cannot convert from 'const _Elem *' to 'const std::exception'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(105,76): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\vcruntime_exception.h(57,5): message : or       'std::exception::exception(const char *const ) noexcept'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(105,61): message : 'std::exception::exception(const char *const ) noexcept': cannot convert argument 1 from 'const _Elem *' to 'const char *const '
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(105,76): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\stdexcept(105,61): message : while trying to match the argument list '(const _Elem *)'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(468,21): error C2665: 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::append': no overloaded function could convert all the argument types
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\xstring(3329,32): message : could be 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::append(const _Elem *const )'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(468,21): message : 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::append(const _Elem *const )': cannot convert argument 1 from 'const char [3]' to 'const _Elem *const '
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(468,29): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\xstring(3131,32): message : or       'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::append(std::initializer_list<_Elem>)'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(468,21): message : 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::append(std::initializer_list<_Elem>)': cannot convert argument 1 from 'const char [3]' to 'std::initializer_list<_Elem>'
1>        with
1>        [
1>            _Elem=wchar_t
1>        ]
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(468,29): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\xstring(3357,32): message : or       'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::append(const _Iter,const _Iter)'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(468,21): message : 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>::append(const _Iter,const _Iter)': expects 2 arguments - 1 provided
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(468,21): message : while trying to match the argument list '(const char [3])'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(487,48): error C2665: 'std::_System_error::_System_error': no overloaded function could convert all the argument types
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(476,5): message : could be 'std::_System_error::_System_error(std::error_code,const std::wstring &)'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(487,48): message : 'std::_System_error::_System_error(std::error_code,const std::wstring &)': cannot convert argument 2 from 'const char [1]' to 'const std::wstring &'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(487,59): message : Reason: cannot convert from 'const char [1]' to 'const std::wstring'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(487,59): message : No constructor could take the source type, or constructor overload resolution was ambiguous
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(487,48): message : while trying to match the argument list '(std::error_code, const char [1])'
1>E:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\include\system_error(491,70): error C2665: 'std::_System_error::_System_error': no overloaded function could convert all the argu

**Comment by intvsteve** [comment]
Sources in this repo have only been built in Visual Studio 2012. Migrating the source and project files to Visual Studio 2022 would be welcome. At present, I do not have Visual Studio 2022.

**Comment by durongze** [comment]
> Sources in this repo have only been built in Visual Studio 2012. Migrating the source and project files to Visual Studio 2022 would be welcome. At present, I do not have Visual Studio 2022.

Ok，thank you.
